#!/usr/bin/env bash
set -euo pipefail

# Minimal interactive installer for a fresh Debian CLI host.
# - installs required OS packages
# - creates venv and installs Python deps
# - writes ai-agent/.env interactively (no secrets committed to git)
# - reminds user to copy GitHub App .pem into place

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

AI_AGENT_DIR="$REPO_ROOT/ai-agent"
VENV_DIR="$AI_AGENT_DIR/venv"
ENV_FILE="$AI_AGENT_DIR/.env"
PEM_TARGET="$AI_AGENT_DIR/github_app/KRT-AI-Agent.pem"

if [[ ! -d "$AI_AGENT_DIR" ]]; then
  echo "Expected ai-agent directory at: $AI_AGENT_DIR" >&2
  exit 1
fi

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  if command -v sudo >/dev/null 2>&1; then
    echo "Re-running with sudo (required for apt installs)..." >&2
    exec sudo -E bash "$0" "$@"
  fi
  echo "This installer needs root for apt installs, but sudo is not available." >&2
  echo "Re-run as root: sudo bash scripts/install_codingai.sh" >&2
  exit 1
fi

if [[ -f /etc/os-release ]]; then
  . /etc/os-release || true
  if [[ "${ID:-}" != "debian" ]]; then
    echo "Warning: this installer was written for Debian; detected ID='${ID:-unknown}'." >&2
  fi
fi

install_node20() {
  if command -v node >/dev/null 2>&1; then
    local ver major
    ver="$(node -v 2>/dev/null || true)"
    major="${ver#v}"
    major="${major%%.*}"
    if [[ "$major" == "20" ]]; then
      return 0
    fi
  fi

  apt-get install -y --no-install-recommends nodejs npm || true

  if command -v node >/dev/null 2>&1; then
    local ver major
    ver="$(node -v 2>/dev/null || true)"
    major="${ver#v}"
    major="${major%%.*}"
    if [[ "$major" == "20" ]]; then
      return 0
    fi
  fi

  echo "Installing Node.js 20 LTS via NodeSource..." >&2
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y --no-install-recommends nodejs
}

apt-get update -y
apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  git \
  gnupg \
  build-essential \
  pkg-config \
  python3 \
  python3-dev \
  python3-pip \
  python3-venv \
  unzip \
  wget \
  docker.io \
  docker-compose-plugin

mkdir -p "$AI_AGENT_DIR/logs" "$REPO_ROOT/workspaces" "$AI_AGENT_DIR/github_app"

install_node20

if command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now docker >/dev/null 2>&1 || true
fi

INSTALL_USER="${INSTALL_USER:-${SUDO_USER:-}}"
if [[ -n "$INSTALL_USER" ]] && id "$INSTALL_USER" >/dev/null 2>&1; then
  groupadd -f docker >/dev/null 2>&1 || true
  usermod -aG docker "$INSTALL_USER" >/dev/null 2>&1 || true
fi

if [[ ! -d "$VENV_DIR" ]]; then
  python3 -m venv "$VENV_DIR"
fi

"$VENV_DIR/bin/pip" install --upgrade pip >/dev/null
"$VENV_DIR/bin/pip" install -r "$AI_AGENT_DIR/requirements.txt"

INSTALL_PLAYWRIGHT_DEPS="${INSTALL_PLAYWRIGHT_DEPS:-1}"
if [[ "$INSTALL_PLAYWRIGHT_DEPS" == "1" ]]; then
  echo "Installing Playwright OS dependencies..." >&2
  # This only installs OS deps; it does not download browsers.
  npx --yes playwright@latest install-deps
fi

prompt() {
  local var="$1"
  local text="$2"
  local def="${3:-}"
  local val=""
  if [[ -n "$def" ]]; then
    read -r -p "$text [$def]: " val
    val="${val:-$def}"
  else
    read -r -p "$text: " val
  fi
  printf '%s=%s\n' "$var" "$val"
}

prompt_secret() {
  local var="$1"
  local text="$2"
  local val=""
  read -r -s -p "$text: " val
  echo
  printf '%s=%s\n' "$var" "$val"
}

if [[ -f "$ENV_FILE" ]]; then
  echo "Found existing $ENV_FILE. It will be backed up and replaced."
  cp -a "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
fi

echo "Writing $ENV_FILE (interactive)..."
{
  echo "# Generated by scripts/install_codingai.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  prompt "GITHUB_APP_ID" "GitHub App ID"
  prompt "GITHUB_INSTALLATION_ID" "GitHub App Installation ID"
  echo
  prompt "LLM_PROVIDER" "LLM provider (openai|local|auto)" "openai"
  prompt "LLM_PROVIDER_ORDER" "Provider order when LLM_PROVIDER=auto" "local,openai"
  prompt "LLM_FALLBACK_ENABLED" "Enable provider fallback (true|false)" "true"
  prompt "LLM_REQUIRE_HEALTHY" "Require healthy provider (true|false)" "true"
  echo
  prompt "OPENAI_BASE_URL" "OpenAI base URL" "https://api.openai.com"
  prompt_secret "OPENAI_API_KEY" "OpenAI API key (leave empty to run local-only)"
  echo
  prompt "LOCAL_LLM_BASE_URL" "Local LLM base URL" "http://127.0.0.1:11434"
  prompt "LOCAL_LLM_API_MODE" "Local LLM API mode (chat|responses)" "chat"
  prompt "LOCAL_LLM_MODEL" "Local LLM model name (optional)" ""
} >"$ENV_FILE"

chmod 600 "$ENV_FILE" || true

echo
echo "IMPORTANT: copy your GitHub App private key (.pem) to:"
echo "  $PEM_TARGET"
echo "You can scp it, then verify permissions (recommended 600)."
echo
if [[ -n "$INSTALL_USER" ]]; then
  echo "Docker group: user '$INSTALL_USER' was added to 'docker'. Re-login for it to take effect."
  echo
fi
echo "Run the control plane + Web UI:"
echo "  cd \"$REPO_ROOT\""
echo "  HOST=0.0.0.0 PORT=8000 scripts/run_control_api.sh"
echo
echo "Health check:"
echo "  curl -s http://127.0.0.1:8000/health"
